### PR TITLE
Styling: table + cells + tabs

### PR DESCRIPTION
**Pull request by hchiam**
## Before:

before

## After:

I can't figure out how to get the conditional scroll shadow to work on the cells, but here's what I tried for now:

after

### CODE REVIEW

**Comment by showduhtung** [comment]
Hey @hchiam this looks really good. Do you think you could make the first two columns (Time and Duty) stationary? And also so that the cells don't explode in size/width when there's a lot less data on one schedule compared to another.

**Comment by hchiam** [comment]
Frozen/fixed columns is doable with `position: sticky` (I'm trying to avoid importing yet another plugin).

And do you mean you want a max width on the table/cells so if there's very few columns, they aren't stretched across the screen?

**Comment by showduhtung** [comment]
Maybe it's best to discuss with Michelle Lin the design? Do you think you can get in touch with her with her thoughts on the design of this schedule component?

Essentially what we're creating is a very excel-like component so that church council members (who are mostly older) can migrate without much difficulty or friction to our app. If you think it'd be helpful, I can open up a conversation between you, me and Michelle

**Comment by hchiam** [comment]
@showduhtung https://codepen.io/hchiam/pen/JjKpjxa (i also messaged Michelle and you in the group Discord)

**Comment by hchiam** [comment]
low res gif:
2-frozen-columns

**Review by showduhtung — APPROVED** [review]

**Comment by showduhtung** [comment]
lgtm!

**Review by hchiam — COMMENTED** [review]
ok i fixed the merge conflict. i tried to do `git pull origin develop` but that broke other things and made the merge more complicated. hopefully nothing breaks on your end. I'll retest the dev branch after merging.
[UPDATE: i tried the dev branch _without_ merging my changes, and i'm seeing the same messages, so I'm going ahead]

**Pull request merged**
